import type {
  AnnotationDocument,
  AnnotationElement,
  DoorElement,
  OpeningRelations,
  WallElement,
  WallRelations,
  WindowElement,
} from '@/types/annotation';

type GeometryElement = WallElement | DoorElement | WindowElement;

const AUTO_ID_PATTERNS = {
  wall: /^wall_[HV]-\d+$/,
  door: /^door_OP-\d+$/,
  window: /^window_OP-\d+$/,
} as const;

function isGeometryElement(element: AnnotationElement): element is GeometryElement {
  return element.type === 'wall' || element.type === 'door' || element.type === 'window';
}

function nowIso(): string {
  return new Date().toISOString();
}

function isAutoGeneratedGeometryId(element: GeometryElement): boolean {
  return AUTO_ID_PATTERNS[element.type].test(element.id);
}

function hostWallId(element: GeometryElement): string {
  if (element.type === 'wall') return '';
  return element.relations && typeof element.relations === 'object' && 'hostWallId' in element.relations
    ? String(element.relations.hostWallId || '')
    : '';
}

function approxEqual(left: number, right: number, tolerance = 2): boolean {
  return Math.abs(left - right) <= tolerance;
}

function geometryEquivalent(left: GeometryElement, right: GeometryElement, tolerance = 2): boolean {
  if (left.type !== right.type || left.geometry.kind !== right.geometry.kind) return false;

  if (left.geometry.kind === 'segment' && right.geometry.kind === 'segment') {
    return (
      approxEqual(left.geometry.x1, right.geometry.x1, tolerance)
      && approxEqual(left.geometry.y1, right.geometry.y1, tolerance)
      && approxEqual(left.geometry.x2, right.geometry.x2, tolerance)
      && approxEqual(left.geometry.y2, right.geometry.y2, tolerance)
      && approxEqual(left.geometry.thicknessPx, right.geometry.thicknessPx, tolerance)
    );
  }

  if (left.geometry.kind === 'rect' && right.geometry.kind === 'rect') {
    return (
      approxEqual(left.geometry.x, right.geometry.x, tolerance)
      && approxEqual(left.geometry.y, right.geometry.y, tolerance)
      && approxEqual(left.geometry.width, right.geometry.width, tolerance)
      && approxEqual(left.geometry.height, right.geometry.height, tolerance)
    );
  }

  return false;
}

function preserveWallRelations(existing: GeometryElement | undefined, fresh: WallElement): WallRelations | undefined {
  if (!existing || existing.type !== 'wall') return fresh.relations;
  const existingRelations = existing.relations as WallRelations | undefined;
  if (!existingRelations) return fresh.relations;
  return {
    ...(fresh.relations || {}),
    ...(existingRelations.surfaceClass ? { surfaceClass: existingRelations.surfaceClass } : {}),
    ...(existingRelations.surfaceClassSource ? { surfaceClassSource: existingRelations.surfaceClassSource } : {}),
    ...(existingRelations.boardSides ? { boardSides: existingRelations.boardSides } : {}),
    ...(typeof existingRelations.excludeFromTakeoff === 'boolean'
      ? { excludeFromTakeoff: existingRelations.excludeFromTakeoff }
      : {}),
  };
}

function preserveAttrs(existing: GeometryElement | undefined, fresh: GeometryElement): GeometryElement['attrs'] {
  if (!existing) return { ...fresh.attrs, geometryEdited: false };
  return {
    ...fresh.attrs,
    locked: existing.attrs.locked,
    visible: existing.attrs.visible,
    notes: existing.attrs.notes,
    name: existing.attrs.name,
    status: existing.attrs.status === 'edited' && !existing.attrs.geometryEdited ? 'edited' : fresh.attrs.status,
    geometryEdited: false,
  };
}

function preserveOpeningRelations(
  existing: GeometryElement | undefined,
  fresh: DoorElement | WindowElement,
): OpeningRelations | undefined {
  if (!existing || (existing.type !== 'door' && existing.type !== 'window')) return fresh.relations;
  const existingRelations = existing.relations as OpeningRelations | undefined;
  if (!existingRelations) return fresh.relations;
  return {
    ...(fresh.relations || {}),
    ...(existingRelations.confidence ? { confidence: existingRelations.confidence } : {}),
    ...(Array.isArray(existingRelations.tagIds) ? { tagIds: existingRelations.tagIds } : {}),
  };
}

function mergeGeometryElement(existing: GeometryElement | undefined, fresh: GeometryElement): GeometryElement {
  if (fresh.type === 'wall') {
    return {
      ...fresh,
      attrs: preserveAttrs(existing, fresh),
      relations: preserveWallRelations(existing, fresh),
    };
  }
  return {
    ...fresh,
    attrs: preserveAttrs(existing, fresh),
    relations: preserveOpeningRelations(existing, fresh),
  };
}

export function hasManualGeometryEdits(
  existingDoc: AnnotationDocument,
  cvDoc?: AnnotationDocument,
): boolean {
  if (existingDoc.meta.hasManualGeometryEdits) return true;

  const geometryElements = existingDoc.elements.filter(isGeometryElement);
  if (!geometryElements.length) return false;

  for (const element of geometryElements) {
    if (element.attrs.geometryEdited) return true;
    if (element.attrs.status === 'new') return true;
    if (!isAutoGeneratedGeometryId(element)) return true;
  }

  if (!cvDoc) return geometryElements.some((element) => element.attrs.status === 'edited');

  const cvById = new Map(
    cvDoc.elements.filter(isGeometryElement).map((element) => [element.id, element]),
  );
  for (const element of geometryElements) {
    if (element.attrs.status !== 'edited') continue;
    const fresh = cvById.get(element.id);
    if (!fresh) return true;
    if (!geometryEquivalent(element, fresh)) return true;
    if (hostWallId(element) !== hostWallId(fresh)) return true;
  }
  return false;
}

export function replaceGeometryFromCV(
  existingDoc: AnnotationDocument,
  cvDoc: AnnotationDocument,
): AnnotationDocument {
  const existingById = new Map(
    existingDoc.elements.filter(isGeometryElement).map((element) => [element.id, element]),
  );

  const mergedGeometry = cvDoc.elements
    .filter(isGeometryElement)
    .map((element) => mergeGeometryElement(existingById.get(element.id), element));
  const preservedNonGeometry = existingDoc.elements.filter((element) => !isGeometryElement(element));
  const validIds = new Set([...mergedGeometry, ...preservedNonGeometry].map((element) => element.id));
  const preservedIssues = existingDoc.issues.filter((issue) => {
    if (!validIds.has(issue.elementId)) return false;
    return !mergedGeometry.some((element) => element.id === issue.elementId);
  });

  return {
    ...existingDoc,
    baseImage: cvDoc.baseImage,
    meta: {
      ...existingDoc.meta,
      source: 'merged',
      updatedAt: nowIso(),
      coordinateSpaceId: cvDoc.meta.coordinateSpaceId,
      hasManualGeometryEdits: false,
    },
    elements: [...mergedGeometry, ...preservedNonGeometry],
    issues: [
      ...preservedIssues,
      ...cvDoc.issues.filter((issue) => validIds.has(issue.elementId)),
    ],
  };
}
